import { Poppins } from "next/font/google";
import SmoothScroll from "../components/SmoothScroll.jsx";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="wrapper">
          <SmoothScroll>{children}</SmoothScroll>
        </div>
      </body>
    </html>
  );
}
